// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://eggvllytfzczgyoiwshi.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVnZ3ZsbHl0Znpjemd5b2l3c2hpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTAwMjEzNDksImV4cCI6MjA2NTU5NzM0OX0.PwhZfX8EBYOJR-E9w7pYBUIVPUG6Zjdxt81tNTdTHrg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);